# Generated by Django 4.1.5 on 2023-04-10 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=100)),
                ('average_rating', models.FloatField(null=True)),
                ('likes', models.IntegerField(default=0)),
                ('serving', models.IntegerField(default=1)),
                ('cooking_time', models.IntegerField()),
                ('preparation_time', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=1000)),
                ('baseRecipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Recipes.recipe')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.recipe')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInstruction',
            fields=[
                ('instruction_id', models.AutoField(primary_key=True, serialize=False)),
                ('instruction', models.CharField(max_length=1000)),
                ('step_number', models.IntegerField()),
                ('time', models.IntegerField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredients_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredients_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('recipe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.FileField(upload_to='media/')),
                ('parent_instruction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Recipes.recipeinstruction')),
                ('parent_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='DietTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(choices=[('V', 'Vegetarian'), ('VG', 'Vegan'), ('GF', 'Gluten Free'), ('DF', 'Dairy Free'), ('O', 'Other')], max_length=2)),
                ('recipe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='CuisineTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(choices=[('A', 'American'), ('B', 'Brazilian'), ('C', 'Chinese'), ('K', 'Korean'), ('J', 'Japanese'), ('O', 'Other')], max_length=2)),
                ('recipe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Recipes.recipe')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('recipe_id', 'user_id'), name='unique_shopping_list'),
        ),
    ]
